training:
  learning_rate: 0.001
  batch_size: 32
  epochs: 50
  pose_clusters: 5
  pose_subspace_dimension: 6
  lmt_features_dimension: 1000
  pca_reduced_dimension: 50

# Dataset 
dataset:
  root_path: "Face-Tracking-and-Recognition-in-Video/data"
  name: "300VW_Dataset_2015_12_14" 
  std_face_size: [48, 48]  # Standard face size as mentioned in the paper (48x48)

# Face tracking parameters
tracking:
  # Energy function weight parameters
  lambda_a: 0.5  # Weight for adaptive appearance model term
  lambda_p: 2.0  # Weight for pose constraint term
  lambda_s: 2.0  # Weight for alignment constraint term
  
  # Particle filtering parameters
  n_particles: 100  # Number of particles for tracking
  sigma: 0.5  # Scale parameter for emission probability (equation 3)

  # Dynamics model parameters
  dynamics_sigmas:
    position: 1.0  # Standard deviation for position (c_x, c_y)
    scale: 0.005    # Standard deviation for scale (rho)
    rotation: 0.005 # Standard deviation for rotation (phi)
  
  # Appearance model parameters
  adaptive_components: 10  # Number of components for adaptive appearance model
  update_rate: 0.5  # Rate at which to update the appearance model
  
  # Visualization parameters
  display_particles: true  # Whether to display particles during tracking
  display_energy: true     # Whether to display energy value